#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev 2>/dev/null || true

echo "========== Test Starts ============"
/test
echo "========== Test Finished =========="
poweroff -f
